[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
dependsOn = ["setup"]
cmds = ["pip install -r railway_requirements.txt"]

[phases.build]
dependsOn = ["install"]
cmds = ["echo 'Build complete - YouTube-only API ready'"]

[start]
cmd = "python api_outreach_service.py"
