
[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
dependsOn = ["setup"]
cmds = ["pip install --break-system-packages fastapi==0.104.1 uvicorn[standard]==0.24.0 aiohttp==3.9.0 pydantic==1.10.13 python-dotenv==1.0.0 requests==2.31.0"]

[phases.build]
dependsOn = ["install"]
cmds = ["echo 'Build complete - YouTube-only API ready'"]

[start]
cmd = "python api_outreach_service.py"
