[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.fastapi", "python311Packages.uvicorn", "python311Packages.aiohttp", "python311Packages.pydantic", "python311Packages.python-dotenv", "python311Packages.requests"]

[phases.install]
dependsOn = ["setup"]
cmds = ["echo 'Dependencies installed via nixpkgs'"]

[phases.build]
dependsOn = ["install"]
cmds = ["echo 'Build complete - YouTube-only API ready'"]

[start]
cmd = "python api_outreach_service.py"
